import './styles/global.scss'
import { Bebas_Neue } from 'next/font/google';
const bebas = Bebas_Neue({ weight: '400', subsets: ['latin'], variable: '--font-bebas' });

export const metadata = {
  title: 'Observation Log Library',
  description: 'Generated by create next app',
  keywords: ['Limbus Company', 'Observation logs', 'Abnormality']
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={bebas.variable}>{children}</body>
    </html>
  );
}
